/**
 * `mc deploy` — the reading, the one question, the script under the lease, and
 * the row it leaves behind.
 *
 * Nothing real is behind any of it: git, the version endpoint, the nightly
 * history, the prompt and `npm run deploy` are all handed in. The lease and
 * the record are the exceptions and deliberately so — they are what this verb
 * exists to leave behind, and MC_HOME and MC_WORK_ROOT both point at throwaway
 * directories here, so the real `repo-lease.js` and the real `deploys.tsv` are
 * written and read back.
 */
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { EventEmitter } from 'node:events';
import { beforeEach, describe, it } from 'node:test';
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  deployPlan, deploySource, deployWorktreePath, leftoverStamps, parseDeployArgs, planLines, readScriptOutput, run,
  spawnDeployDefault, worktreeState,
} from '../../../src/mc/commands/deploy.js';
import { mainWorktree } from '../../../src/mc/git.js';
import { lastAttempt, lastDeploy, readDeploys, recordStart } from '../../../src/mc/deploys.js';
import { claimLease, readLease, releaseLease } from '../../../src/mc/repo-lease.js';

const SHA = '1a2b3c4d5e6f70819293a4b5c6d7e8f900112233';
const LIVE = '9f8e7d6c5b4a39281706f5e4d3c2b1a099887766';
const PATH = '/tmp/does-not-exist/memoro';
const REPOS = [{ name: 'memoro', path: PATH }, { name: 'memoro-cli', path: '/tmp/does-not-exist/memoro-cli' }];

/** The colours `deploy.mjs` prints its landmarks in, so the parsing is tested
 * against the bytes rather than against a cleaned-up version of them. */
const CYAN = '\u001B[36m'; const RESET = '\u001B[0m'; const DIM = '\u001B[2m';
const GREEN = '\u001B[32m'; const BOLD = '\u001B[1m'; const RED = '\u001B[31m'; const YELLOW = '\u001B[33m';
const stepLine = (label) => `\n${CYAN}▸ ${label}${RESET}\n`;

/** A `deploy.mjs` that gets as far as `stopAt` and then either finishes or
 * falls over, printing what the real one prints on the way. */
function fakeScript({
  steps = [], build = '23533', commit = SHA, verify = true, code = 0, failure = '', production = '', retries = 0,
} = {}) {
  return async ({ onOutput }) => {
    for (const label of steps) onOutput(stepLine(label));
    for (let i = 0; i < retries; i += 1) onOutput(`${YELLOW}  ↻ wrangler deploy failed after 0s: fetch failed.${RESET}\n`);
    if (code === 0) {
      if (verify) onOutput(`${DIM}  Live /api/version verified: build ${build} · ${commit}${RESET}\n`);
      onOutput(`\n${GREEN}${BOLD}✓ Deploy complete${RESET} ${DIM}build ${build} · ${commit}${RESET}\n`);
    } else {
      onOutput(`\n${RED}✗ Deploy failed${RESET}\n${DIM}${failure}${RESET}\n`);
      if (production) onOutput(`\n  ${BOLD}Production ${RESET}${production}\n`);
    }
    return { code };
  };
}

const FULL_RUN = ['Deploy source preflight', 'wrangler deploy', 'wrangler deploy (tail-worker)', 'Verify live version'];

/** `git diff HEAD --unified=0` of the tree the deploy of 957cebb left on
 * 2026-10-05, when it was killed between stamping and restoring. */
const STAMP_DIFF = [
  'diff --git a/public/sw.js b/public/sw.js',
  '--- a/public/sw.js',
  '+++ b/public/sw.js',
  '@@ -17 +17 @@',
  "-const CACHE_VERSION = 'dev-brand-thinker-warm-relief01';",
  "+const CACHE_VERSION = 'v957cebb3d0b7';",
  'diff --git a/src/version.js b/src/version.js',
  '--- a/src/version.js',
  '+++ b/src/version.js',
  '@@ -1,20 +1,6 @@',
  '-/**',
  '- * Worker version constants.',
  '+// Auto-generated by scripts/inject-version.mjs at deploy time. Do not edit.',
  ' export const VERSION = "1.0.0";',
  '-export const COMMIT = "dev";',
  '+export const COMMIT = "957cebb";',
  '+export const COMMIT_FULL = "957cebb3d0b7b294abfe5bb38bcb100eafa99b01";',
  '+export const BUILD_TIME = "2026-10-05T20:05:01.000Z";',
  '+export const BUILD_NUMBER = 24804;',
].join('\n');

let work = null;

/**
 * The clock `mc merge`'s wait tests use: `sleep` moves `now` on by what it
 * was asked to sleep, so eight minutes of polling run in no time. `onSleep`
 * is what happens in the world while the deploy sleeps, given the count.
 */
function fakeClock({ onSleep = () => {} } = {}) {
  let at = Date.parse('2026-10-07T12:00:00Z');
  let count = 0;
  return {
    now: () => new Date(at),
    sleep: async (ms) => { at += ms; count += 1; onSleep(count); },
    slept: () => count,
  };
}

function io() {
  const out = { stdout: '', stderr: '' };
  return { out, stdout: { write: (s) => { out.stdout += s; } }, stderr: { write: (s) => { out.stderr += s; } } };
}

/** Where `main` is checked out on the machine the test is describing. */
const MAIN_WT = '/tmp/does-not-exist/mc/plan/msr-core/memoro';
const porcelain = (stanzas) => stanzas.map((lines) => lines.join('\n')).join('\n\n');
const worktreeList = (mainAt = MAIN_WT) => porcelain([
  [`worktree ${PATH}`, 'HEAD 0000000000000000000000000000000000000000', 'branch refs/heads/language-content-open-decisions'],
  ...(mainAt ? [[`worktree ${mainAt}`, `HEAD ${SHA}`, 'branch refs/heads/main']] : []),
  ['worktree /tmp/does-not-exist/scratch', 'HEAD 1111111111111111111111111111111111111111', 'detached'],
]);

/**
 * git as the verb uses it: fetch, rev-parse, log, rev-list, plus the three
 * readings of the worktree it will run in. `state` answers `status --porcelain`
 * and the two `rev-list --count` ranges per worktree path, so a test says where
 * `main` is *and* what state it is in without a repository anywhere.
 */
function fakeGit({
  sha = SHA, counts = {}, subject = 'the change that would ship', fetch = true,
  worktrees = worktreeList(), state = {}, localMain = true, add = '', ff = '', diff = null,
} = {}) {
  const calls = [];
  const at = (cwd) => state[cwd] || { dirty: [], ahead: 0, behind: 0 };
  const git = (cwd, args) => {
    calls.push({ cwd, args });
    if (args[0] === 'fetch') return fetch ? '' : null;
    if (args[0] === 'rev-parse') return sha;
    if (args[0] === 'log') return subject;
    if (args[0] === 'worktree' && args[1] === 'list') return worktrees;
    if (args[0] === 'worktree' && args[1] === 'add') return add;
    if (args[0] === 'show-ref') return localMain ? '' : null;
    if (args[0] === 'status') return at(cwd).dirty.join('\n');
    if (args[0] === 'merge') return ff;
    if (args[0] === 'clean') return '';
    if (args[0] === 'diff') return diff;
    if (args[0] === 'rev-list') {
      const range = args.at(-1);
      if (range === 'origin/main..HEAD') return String(at(cwd).ahead);
      if (range === 'HEAD..origin/main') return String(at(cwd).behind);
      return Object.hasOwn(counts, range) ? String(counts[range]) : null;
    }
    return null;
  };
  git.calls = calls;
  return git;
}

const noNightly = () => ({ runs: 0, last: null, measured: null, red: [] });
const nightlyOn = (commit, red = 0) => () => ({
  runs: 1, last: null, red: [],
  measured: { at: '2026-09-03T02:00:00Z', outcome: red ? 'failed' : 'passed', commit, tests: 900, red },
});

function deps(extra = {}) {
  return {
    env: { ...process.env, MC_WORK_ROOT: work },
    repos: REPOS,
    git: fakeGit({ counts: { [`${LIVE}..${SHA}`]: 6 } }),
    fetchVersion: async () => ({ commit: LIVE, build: 812, build_time: '2026-09-01T10:00:00Z' }),
    lastDeploy: () => null,
    nightly: nightlyOn(SHA),
    interactive: () => true,
    ask: () => 'y',
    spawnDeploy: async () => ({ code: 0 }),
    ...extra,
  };
}

beforeEach(() => {
  releaseLease({ repoPath: PATH, force: true });
  // A work root per test: the record is written for real, and one test's rows
  // are not another's.
  work = mkdtempSync(join(tmpdir(), 'mc-deploy-work-'));
});

describe('mc deploy — the arguments', () => {
  it('takes --dry-run and --json, and nothing positional', () => {
    assert.deepEqual(parseDeployArgs(['--dry-run']), { dryRun: true, json: false });
    assert.match(parseDeployArgs(['memoro']).error, /takes no arguments \(memoro\)/u);
    assert.match(parseDeployArgs(['--force']).error, /unknown flag: --force/u);
  });

  it('refuses a stray argument with usage, exit 2', async () => {
    const { out, stdout, stderr } = io();
    assert.equal(await run(['memoro'], { ...deps(), stdout, stderr }), 2);
    assert.match(out.stderr, /mc deploy \[--dry-run\]/u);
  });
});

describe('mc deploy — what it says before it asks', () => {
  it('names the sha, the last deployed sha and the gap', async () => {
    const plan = await deployPlan({
      path: PATH,
      env: {},
      git: fakeGit({ counts: { [`${LIVE}..${SHA}`]: 6 } }),
      fetchVersion: async () => ({ commit: LIVE, build: 812, build_time: '2026-09-01T10:00:00Z' }),
      lastDeploy: () => null,
      nightly: nightlyOn(SHA),
    });
    assert.equal(plan.sha, SHA);
    assert.equal(plan.last.sha, LIVE);
    assert.equal(plan.last.source, 'api/version');
    assert.equal(plan.gap, 6);
    const text = planLines(plan).join('\n');
    assert.match(text, new RegExp(`would deploy memoro ${SHA}`, 'u'));
    assert.match(text, /live now 9f8e7d6 \(build 812\) — api\/version/u);
    assert.match(text, /6 commits would ship/u);
  });

  it('prefers the row mc wrote over what production says it is', async () => {
    const plan = await deployPlan({
      path: PATH,
      env: {},
      git: fakeGit({ counts: { [`${LIVE}..${SHA}`]: 2 } }),
      fetchVersion: async () => { throw new Error('must not be asked'); },
      lastDeploy: () => ({ sha: LIVE, build: '77', ended: '2026-09-02T08:00:00Z', outcome: 'deployed' }),
      nightly: noNightly,
    });
    assert.equal(plan.last.source, 'deploys.tsv');
    assert.equal(plan.gap, 2);
  });

  it('says plainly when the nightly measured another tree, and still asks', async () => {
    const older = 'abc1234000000000000000000000000000000000';
    const { out, stdout, stderr } = io();
    let asked = 0;
    const code = await run([], {
      ...deps({
        git: fakeGit({ counts: { [`${LIVE}..${SHA}`]: 6, [`${older}..${SHA}`]: 6 } }),
        nightly: nightlyOn(older),
        ask: () => { asked += 1; return 'y'; },
      }),
      stdout,
      stderr,
    });
    assert.equal(code, 0);
    assert.equal(asked, 1);
    assert.match(out.stdout, /the nightly measured abc1234, 6 commits ago; this tree was not measured whole/u);
  });

  it('says the nightly measured this tree when it did', async () => {
    const { out, stdout, stderr } = io();
    await run(['--dry-run'], { ...deps(), stdout, stderr });
    assert.match(out.stdout, /the nightly measured this tree 1a2b3c4 — 0 red/u);
  });

  it('--dry-run stops before the question, takes no lease and runs nothing', async () => {
    const { out, stdout, stderr } = io();
    let asked = 0;
    let ran = 0;
    const code = await run(['--dry-run'], {
      ...deps({ ask: () => { asked += 1; return 'y'; }, spawnDeploy: async () => { ran += 1; return { code: 0 }; } }),
      stdout,
      stderr,
    });
    assert.equal(code, 0);
    assert.equal(asked, 0);
    assert.equal(ran, 0);
    assert.equal(readLease(PATH).held, false);
    assert.match(out.stdout, /--dry-run — nothing was deployed/u);
  });

  it('--json is the same reading as one object', async () => {
    const { out, stdout, stderr } = io();
    await run(['--dry-run', '--json'], { ...deps(), stdout, stderr });
    const json = JSON.parse(out.stdout);
    assert.equal(json.sha, SHA);
    assert.equal(json.gap, 6);
    assert.equal(json.dry_run, true);
    assert.equal(json.nightly.this_tree, true);
  });
});

describe('where main is — the lookup over git worktree list --porcelain', () => {
  it('finds the stanza whose branch is refs/heads/main', () => {
    assert.equal(mainWorktree(worktreeList()), MAIN_WT);
  });

  it('is null when no worktree has main out', () => {
    assert.equal(mainWorktree(worktreeList(null)), null);
  });

  it('skips detached and bare stanzas, and keeps a path with a space', () => {
    const text = porcelain([
      ['worktree /tmp/repo.git', 'bare'],
      ['worktree /tmp/some other/place', `HEAD ${SHA}`, 'branch refs/heads/main'],
      ['worktree /tmp/detached', `HEAD ${SHA}`, 'detached'],
    ]);
    assert.equal(mainWorktree(text), '/tmp/some other/place');
  });

  it('is not fooled by a branch whose name merely starts with main', () => {
    const text = porcelain([['worktree /tmp/a', `HEAD ${SHA}`, 'branch refs/heads/main-red-fix']]);
    assert.equal(mainWorktree(text), null);
  });

  it('is null on nothing at all, rather than a crash', () => {
    assert.equal(mainWorktree(''), null);
    assert.equal(mainWorktree(null), null);
  });
});

describe('mc deploy — the worktree the script runs in', () => {
  const MINE = deployWorktreePath(process.env);

  it('uses the worktree that has main, wherever that is', () => {
    const git = fakeGit();
    assert.deepEqual(deploySource({ path: PATH, git, env: process.env, create: true }), {
      worktree: MAIN_WT, created: false, absent: false, failed: false,
    });
    assert.equal(git.calls.some((call) => call.args[1] === 'add'), false, 'nothing is made when main is already out');
  });

  it('makes mc\'s own worktree under MC_HOME when main is checked out nowhere', () => {
    const git = fakeGit({ worktrees: worktreeList(null) });
    const source = deploySource({ path: PATH, git, env: process.env, create: true });
    assert.deepEqual(source, { worktree: MINE, created: true, absent: false, failed: false });
    assert.match(MINE, /\/deploy\/memoro$/u);
    assert.equal(MINE.startsWith(process.env.MC_HOME), true, 'under mc home, never under ~/mc');
    const add = git.calls.find((call) => call.args[1] === 'add');
    assert.equal(add.cwd, PATH, 'the checkout that owns the worktrees makes it');
    assert.deepEqual(add.args, ['worktree', 'add', MINE, 'main']);
  });

  it('makes the branch from origin/main when main does not exist locally', () => {
    const git = fakeGit({ worktrees: worktreeList(null), localMain: false });
    deploySource({ path: PATH, git, env: process.env, create: true });
    const add = git.calls.find((call) => call.args[1] === 'add');
    assert.deepEqual(add.args, ['worktree', 'add', '-b', 'main', MINE, 'origin/main']);
  });

  it('makes nothing without create — that is what --dry-run reports', () => {
    const git = fakeGit({ worktrees: worktreeList(null) });
    assert.deepEqual(deploySource({ path: PATH, git, env: process.env }), {
      worktree: MINE, created: false, absent: true, failed: false,
    });
    assert.equal(git.calls.some((call) => call.args[1] === 'add'), false);
  });

  it('says so rather than throwing when git worktree add fails', () => {
    const git = fakeGit({ worktrees: worktreeList(null), add: null });
    assert.deepEqual(deploySource({ path: PATH, git, env: process.env, create: true }), {
      worktree: MINE, created: false, absent: true, failed: true,
    });
  });

  it('reads dirty, ahead and behind in the worktree itself', () => {
    const git = fakeGit({ state: { [MAIN_WT]: { dirty: [' M src/a.js', '?? b.txt'], ahead: 2, behind: 7 } } });
    assert.deepEqual(worktreeState({ worktree: MAIN_WT, git }), {
      dirty: [' M src/a.js', '?? b.txt'], ahead: 2, behind: 7,
    });
    assert.equal(git.calls.every((call) => call.cwd === MAIN_WT), true);
  });
});

describe('mc deploy — every case of where main is', () => {
  const MINE = deployWorktreePath(process.env);

  const ranIn = async (extra, argv = []) => {
    const seen = [];
    const { out, stdout, stderr } = io();
    const code = await run(argv, {
      ...deps({ ...extra, spawnDeploy: async (options) => { seen.push(options); return { code: 0 }; } }),
      stdout,
      stderr,
    });
    return { code, seen, out };
  };

  it('main in another worktree: the reading names it and the script runs there', async () => {
    const { code, seen, out } = await ranIn({});
    assert.equal(code, 0);
    assert.equal(seen[0].cwd, MAIN_WT);
    assert.match(out.stdout, new RegExp(`mc: from ${MAIN_WT} — main at origin/main`, 'u'));
  });

  it('main behind origin/main: fast-forwarded under the lease, then the script runs there', async () => {
    const git = fakeGit({
      counts: { [`${LIVE}..${SHA}`]: 6 },
      state: { [MAIN_WT]: { dirty: [], ahead: 0, behind: 3 } },
    });
    const { code, seen, out } = await ranIn({ git });
    assert.equal(code, 0);
    assert.equal(seen[0].cwd, MAIN_WT);
    assert.match(out.stdout, /main, 3 behind origin\/main, fast-forwarded before the script runs/u);
    const ff = git.calls.find((call) => call.args[0] === 'merge');
    assert.deepEqual(ff, { cwd: MAIN_WT, args: ['merge', '--ff-only', 'origin/main'] });
    assert.match(out.stdout, /fast-forwarded main in .* to 1a2b3c4/u);
  });

  /**
   * A repository whose `origin/main` moves: the runner lands #11913 between the
   * reading and the yes, as it did on 2026-09-19. HEAD is tracked per worktree
   * and `merge --ff-only origin/main` moves it to whatever `origin/main` names
   * *now* — which is what ships, and so what the row has to say.
   */
  const LATER = '8e431c6aa0b1c2d3e4f5061728394a5b6c7d8e9f';
  function movingGit({ head = SHA, behind = 3 } = {}) {
    const base = fakeGit({ counts: { [`${LIVE}..${SHA}`]: 6 }, state: { [MAIN_WT]: { dirty: [], ahead: 0, behind } } });
    let origin = SHA;
    let at = head;
    const git = (cwd, args) => {
      if (args[0] === 'rev-parse') {
        base.calls.push({ cwd, args });
        return args.at(-1) === 'HEAD' ? at : origin;
      }
      if (args[0] === 'merge') {
        base.calls.push({ cwd, args });
        at = args.at(-1) === 'origin/main' ? origin : args.at(-1);
        return '';
      }
      return base(cwd, args);
    };
    git.calls = base.calls;
    git.land = () => { origin = LATER; };
    return git;
  }

  it('origin/main moving after the question: main goes to origin/main, and the row and the terminal name what shipped', async () => {
    const git = movingGit();
    const { code, seen, out } = await ranIn({ git, ask: () => { git.land(); return 'y'; } });
    assert.equal(code, 0);
    assert.deepEqual(git.calls.find((call) => call.args[0] === 'merge').args, ['merge', '--ff-only', 'origin/main']);
    assert.equal(seen[0].sha, LATER, 'the script is handed the sha the tree stands on');
    assert.match(out.stdout, /fast-forwarded main in .* to 8e431c6\n/u);
    assert.match(out.stdout, /mc: main moved to 8e431c6 since the question; deploying 8e431c6\n/u);
    assert.equal(out.stderr, '', 'informational, not a warning');
    const row = lastDeploy({ MC_WORK_ROOT: work });
    assert.equal(row.sha, LATER, 'the row records the commit that went out');
  });

  it('main already moved on by somebody else: nothing to merge, and the row still names what is there', async () => {
    const git = movingGit({ head: LATER, behind: 0 });
    const { code, out } = await ranIn({ git, ask: () => { git.land(); return 'y'; } });
    assert.equal(code, 0);
    assert.equal(git.calls.some((call) => call.args[0] === 'merge'), false);
    assert.doesNotMatch(out.stdout, /fast-forwarded/u);
    assert.match(out.stdout, /main moved to 8e431c6 since the question; deploying 8e431c6/u);
    assert.equal(lastDeploy({ MC_WORK_ROOT: work }).sha, LATER);
  });

  it('origin/main standing still: no line about it moving', async () => {
    const git = movingGit();
    const { out } = await ranIn({ git });
    assert.match(out.stdout, /fast-forwarded main in .* to 1a2b3c4/u);
    assert.doesNotMatch(out.stdout, /main moved/u);
    assert.equal(lastDeploy({ MC_WORK_ROOT: work }).sha, SHA);
  });

  it('main dirty: a refused row naming the path and the files, and nothing runs', async () => {
    const git = fakeGit({
      counts: { [`${LIVE}..${SHA}`]: 6 },
      state: { [MAIN_WT]: { dirty: [' M src/app.js', '?? scratch.txt'], ahead: 0, behind: 0 } },
    });
    const { code, seen, out } = await ranIn({ git });
    assert.equal(code, 1);
    assert.equal(seen.length, 0, 'nothing is deployed out of a dirty tree');
    assert.equal(git.calls.some((call) => call.args[0] === 'merge'), false, 'and nobody\'s work is moved');
    const row = lastAttempt({ MC_WORK_ROOT: work });
    assert.equal(row.outcome, 'refused');
    assert.equal(row.note, `main is dirty in ${MAIN_WT} — 2 file(s)`);
    assert.match(out.stderr, /M src\/app\.js/u);
  });

  it('main dirty with nothing but a stopped deploy\'s stamps: it runs, and says so', async () => {
    const git = fakeGit({
      counts: { [`${LIVE}..${SHA}`]: 6 },
      state: { [MAIN_WT]: { dirty: ['M public/sw.js', ' M src/version.js'], ahead: 0, behind: 0 } },
      diff: STAMP_DIFF,
    });
    const { code, seen, out } = await ranIn({ git });
    assert.equal(code, 0);
    assert.equal(seen.length, 1, 'deploy.mjs restores the stamps itself before it builds');
    assert.match(out.stdout, /with the stamps a stopped deploy left in public\/sw\.js and src\/version\.js/u);
    assert.equal(lastAttempt({ MC_WORK_ROOT: work }).outcome, 'deployed');
  });

  it('mc\'s own main with nothing but untracked files: removed under the lease, said, and it runs', async () => {
    const git = fakeGit({
      worktrees: worktreeList(MINE),
      counts: { [`${LIVE}..${SHA}`]: 6 },
      state: { [MINE]: { dirty: ['?? artifacts/', '?? public/sdk/'], ahead: 0, behind: 0 } },
    });
    const { code, seen, out } = await ranIn({ git });
    assert.equal(code, 0);
    assert.equal(seen.length, 1);
    assert.match(out.stdout, /mc's own main, 2 untracked paths removed before the script runs/u);
    assert.deepEqual(git.calls.find((call) => call.args[0] === 'clean'), { cwd: MINE, args: ['clean', '-fd'] });
    assert.match(out.stdout, /removed 2 untracked paths from mc's own main worktree:\nmc: {3}artifacts\/\nmc: {3}public\/sdk\//u);
  });

  /** A fast-forward that brings in a commit dropping lines from `.gitignore`:
   * clean before the merge, untracked files after it (#13137, 2026-10-09). */
  function ignoreDroppingGit(worktree) {
    const base = fakeGit({
      worktrees: worktreeList(worktree),
      counts: { [`${LIVE}..${SHA}`]: 6 },
      state: { [worktree]: { dirty: [], ahead: 0, behind: 1 } },
    });
    let merged = false;
    const git = (cwd, args) => {
      if (args[0] === 'merge') merged = true;
      if (args[0] === 'status' && merged) {
        base.calls.push({ cwd, args });
        return '?? artifacts/\n?? public/sdk/';
      }
      return base(cwd, args);
    };
    git.calls = base.calls;
    return git;
  }

  it('mc\'s own main dirtied by the fast-forward: the untracked files go and the script runs', async () => {
    const git = ignoreDroppingGit(MINE);
    const { code, seen, out } = await ranIn({ git });
    assert.equal(code, 0);
    assert.equal(seen.length, 1);
    const order = git.calls.map((call) => call.args[0]);
    assert.ok(order.indexOf('merge') < order.indexOf('clean'), 'cleaned after the fast-forward');
    assert.match(out.stdout, /removed 2 untracked paths from mc's own main worktree/u);
  });

  it('somebody\'s main dirtied by the fast-forward: a refused row naming the files, nothing removed, nothing runs', async () => {
    const git = ignoreDroppingGit(MAIN_WT);
    const { code, seen, out } = await ranIn({ git });
    assert.equal(code, 1);
    assert.equal(seen.length, 0);
    assert.equal(git.calls.some((call) => call.args[0] === 'clean'), false, 'nobody else\'s tree is cleaned');
    const row = lastAttempt({ MC_WORK_ROOT: work });
    assert.equal(row.outcome, 'refused');
    assert.equal(row.note, `main is dirty in ${MAIN_WT} after the fast-forward — 2 untracked file(s)`);
    assert.match(out.stderr, /the fast-forward left 2 untracked files .*\nmc: {3}artifacts\//u);
  });

  it('mc\'s own main with a modified tracked file: still refused, nothing removed', async () => {
    const git = fakeGit({
      worktrees: worktreeList(MINE),
      counts: { [`${LIVE}..${SHA}`]: 6 },
      state: { [MINE]: { dirty: [' M src/app.js', '?? scratch.txt'], ahead: 0, behind: 0 } },
    });
    const { code, seen } = await ranIn({ git });
    assert.equal(code, 1);
    assert.equal(seen.length, 0);
    assert.equal(git.calls.some((call) => call.args[0] === 'clean'), false);
  });

  it('main with commits not on origin/main: a refused row, and nothing runs', async () => {
    const git = fakeGit({
      counts: { [`${LIVE}..${SHA}`]: 6 },
      state: { [MAIN_WT]: { dirty: [], ahead: 2, behind: 0 } },
    });
    const { code, seen, out } = await ranIn({ git });
    assert.equal(code, 1);
    assert.equal(seen.length, 0);
    const row = lastAttempt({ MC_WORK_ROOT: work });
    assert.equal(row.outcome, 'refused');
    assert.equal(row.note, `main in ${MAIN_WT} has 2 commit(s) not on origin/main`);
    assert.match(out.stderr, /which is not that tree/u);
  });

  it('main checked out nowhere: mc makes its own worktree, says so, and runs there', async () => {
    const git = fakeGit({ worktrees: worktreeList(null), counts: { [`${LIVE}..${SHA}`]: 6 } });
    const { code, seen, out } = await ranIn({ git });
    assert.equal(code, 0);
    assert.equal(seen[0].cwd, MINE);
    assert.deepEqual(git.calls.find((call) => call.args[1] === 'add'), {
      cwd: PATH, args: ['worktree', 'add', MINE, 'main'],
    });
    assert.match(out.stdout, /made mc's own main worktree at .*\/deploy\/memoro/u);
  });

  it('mc\'s worktree already there: found like any other, and made a second time by nobody', async () => {
    const git = fakeGit({ worktrees: worktreeList(MINE), counts: { [`${LIVE}..${SHA}`]: 6 } });
    const { code, seen } = await ranIn({ git });
    assert.equal(code, 0);
    assert.equal(seen[0].cwd, MINE);
    assert.equal(git.calls.some((call) => call.args[1] === 'add'), false);
  });

  it('--dry-run names the worktree, makes nothing and moves nothing', async () => {
    const git = fakeGit({
      counts: { [`${LIVE}..${SHA}`]: 6 },
      state: { [MAIN_WT]: { dirty: [], ahead: 0, behind: 4 } },
    });
    const { out } = await ranIn({ git }, ['--dry-run']);
    assert.match(out.stdout, new RegExp(`mc: from ${MAIN_WT} — main, 4 behind`, 'u'));
    assert.equal(git.calls.some((call) => call.args[0] === 'merge'), false);
    assert.equal(git.calls.some((call) => call.args[1] === 'add'), false);
  });

  it('--dry-run with main nowhere reports the worktree it would make, and makes none', async () => {
    const git = fakeGit({ worktrees: worktreeList(null), counts: { [`${LIVE}..${SHA}`]: 6 } });
    const { out } = await ranIn({ git }, ['--dry-run']);
    assert.match(out.stdout, /mc's own main worktree, made before the script runs/u);
    assert.equal(git.calls.some((call) => call.args[1] === 'add'), false);
  });

  it('--json carries the worktree and how far behind it is', async () => {
    const git = fakeGit({
      counts: { [`${LIVE}..${SHA}`]: 6 },
      state: { [MAIN_WT]: { dirty: [], ahead: 0, behind: 4 } },
    });
    const { out } = await ranIn({ git }, ['--dry-run', '--json']);
    const json = JSON.parse(out.stdout);
    assert.equal(json.worktree, MAIN_WT);
    assert.equal(json.behind, 4);
    assert.equal(json.path, PATH, 'the reads and the lease are still ~/memoro');
  });

  it('git worktree add that fails is a refused row, not a deploy from the wrong tree', async () => {
    const git = fakeGit({ worktrees: worktreeList(null), add: null, counts: { [`${LIVE}..${SHA}`]: 6 } });
    const { code, seen } = await ranIn({ git });
    assert.equal(code, 1);
    assert.equal(seen.length, 0);
    assert.match(lastAttempt({ MC_WORK_ROOT: work }).note, /could not make mc's own main worktree/u);
  });
});

describe('mc deploy — the question', () => {
  it('asks once, naming the sha, and a no runs nothing', async () => {
    const { out, stdout, stderr } = io();
    const asks = [];
    let ran = 0;
    const code = await run([], {
      ...deps({
        ask: (prompt) => { asks.push(prompt); return 'n'; },
        spawnDeploy: async () => { ran += 1; return { code: 0 }; },
      }),
      stdout,
      stderr,
    });
    assert.equal(code, 1);
    assert.deepEqual(asks, ['deploy 1a2b3c4 to production? [y/N]']);
    assert.equal(ran, 0);
    assert.equal(readLease(PATH).held, false);
    assert.match(out.stdout, /nothing was deployed/u);
  });

  it('Enter is a no: only y or yes deploys', async () => {
    let ran = 0;
    for (const answer of [null, '', 'no', 'sure', 'Y']) {
      const { stdout, stderr } = io();
      // eslint-disable-next-line no-await-in-loop
      const code = await run([], {
        ...deps({ ask: () => answer, spawnDeploy: async () => { ran += 1; return { code: 0 }; } }),
        stdout,
        stderr,
      });
      assert.equal(code, answer === 'Y' ? 0 : 1, `answer ${JSON.stringify(answer)}`);
    }
    assert.equal(ran, 1);
  });

  it('without a terminal it deploys nothing and exits 2', async () => {
    const { out, stdout, stderr } = io();
    let ran = 0;
    const code = await run([], {
      ...deps({ interactive: () => false, spawnDeploy: async () => { ran += 1; return { code: 0 }; } }),
      stdout,
      stderr,
    });
    assert.equal(code, 2);
    assert.equal(ran, 0);
    assert.match(out.stderr, /no terminal here to ask/u);
  });
});

describe('mc deploy — the script beside the lease', () => {
  it('runs npm run deploy in the worktree that is main, with the environment, the lease already free and the row written', async () => {
    const { stdout, stderr } = io();
    const seen = [];
    const env = { ...process.env, MC_WORK_ROOT: work, MEMORO_DEPLOY_CONTAINERS: 'always' };
    const code = await run([], {
      ...deps({ env }),
      stdout,
      stderr,
      spawnDeploy: async (options) => {
        seen.push({ ...options, lease: readLease(PATH), row: lastAttempt({ MC_WORK_ROOT: work }) });
        return { code: 0 };
      },
    });
    assert.equal(code, 0);
    assert.equal(seen.length, 1);
    assert.equal(seen[0].cwd, MAIN_WT, 'the spawn runs where main is, not where the reads and the lease are');
    assert.equal(seen[0].env.MEMORO_DEPLOY_CONTAINERS, 'always');
    assert.equal(seen[0].lease.held, false, 'the lease covers the read of the sha, not the build');
    assert.equal(seen[0].row.outcome, 'running');
    assert.equal(seen[0].row.sha, SHA);
    assert.equal(readLease(PATH).held, false);
  });

  it('a throw after the release does not release a lease a merge round took in between', async () => {
    const { stdout, stderr } = io();
    const releases = [];
    await assert.rejects(run([], {
      ...deps({
        releaseLease: (args) => { releases.push(args); return releaseLease(args); },
        spawnDeploy: async () => {
          claimLease({ repoPath: PATH, errand: 'merge memoro #812', holder: { name: 'runner', kind: 'work-area' } });
          throw new Error('spawn blew up');
        },
      }),
      stdout,
      stderr,
    }), /spawn blew up/u);
    assert.equal(releases.length, 1, 'released once, before the spawn, and not again in the finally');
    const lease = readLease(PATH);
    assert.equal(lease.held, true);
    assert.equal(lease.holder, 'runner');
    assert.equal(lease.errand, 'merge memoro #812');
    assert.equal(readDeploys({ MC_WORK_ROOT: work })[0].outcome, 'failed');
  });

  it('releases the lease when something under it throws', async () => {
    const { stdout, stderr } = io();
    const git = fakeGit({ state: { [MAIN_WT]: { dirty: [], ahead: 0, behind: 2 } } });
    const throwing = (cwd, args) => {
      if (args[0] === 'merge') throw new Error('git blew up');
      return git(cwd, args);
    };
    await assert.rejects(run([], { ...deps({ git: throwing }), stdout, stderr }), /git blew up/u);
    assert.equal(readLease(PATH).held, false);
  });

  it('returns the script\'s exit code, and releases the lease anyway', async () => {
    const { out, stdout, stderr } = io();
    const code = await run([], { ...deps({ spawnDeploy: async () => ({ code: 17 }) }), stdout, stderr });
    assert.equal(code, 17);
    assert.equal(readLease(PATH).held, false);
    assert.match(out.stderr, /npm run deploy exited 17/u);
  });

  it('releases the lease when the spawn itself throws', async () => {
    const { stdout, stderr } = io();
    await assert.rejects(run([], {
      ...deps({ spawnDeploy: async () => { throw new Error('spawn blew up'); } }),
      stdout,
      stderr,
    }), /spawn blew up/u);
    assert.equal(readLease(PATH).held, false);
  });

  it('waits eight minutes for a lease that stays held, then refuses with exit 3 and runs nothing', async () => {
    claimLease({ repoPath: PATH, errand: 'gate round #591', holder: { name: 'runner', kind: 'work-area' } });
    const { out, stdout, stderr } = io();
    let ran = 0;
    const code = await run([], {
      ...deps({ spawnDeploy: async () => { ran += 1; return { code: 0 }; }, ...fakeClock() }),
      stdout,
      stderr,
    });
    assert.equal(code, 3);
    assert.equal(ran, 0);
    assert.match(out.stderr, /is held by runner for “gate round #591” — waiting for the window/u);
    assert.equal(out.stderr.match(/waiting for the window/gu).length, 1, 'said once, not every poll');
    assert.match(out.stderr, /still waiting for .*, held by runner for “gate round #591”, after 8 min — run this again; nothing was deployed/u);
    assert.equal(readLease(PATH).holder, 'runner');
  });

  it('says so and deploys nothing when the checkout has no origin/main', async () => {
    const { out, stdout, stderr } = io();
    const code = await run([], { ...deps({ git: fakeGit({ sha: null }) }), stdout, stderr });
    assert.equal(code, 1);
    assert.match(out.stderr, /has no origin\/main/u);
  });
});

/**
 * The window and the other deploy. Since step 1 the lease covers seconds of a
 * deploy, so a held one is a merge round's gate to wait out, and what keeps two
 * deploys apart is the record: a `running` row whose process is alive.
 */
describe('mc deploy — waiting for the window, and one deploy at a time', () => {
  it('waits for a held lease, takes it when released, and ships the sha read after the fast-forward', async () => {
    claimLease({ repoPath: PATH, errand: 'merge round for memoro #812', holder: { name: 'runner', kind: 'work-area' } });
    // The merge round lands #812 while it holds the lease: origin/main moves,
    // and the deploy fast-forwards to it once its turn comes.
    const LANDED = '8e431c6aa0b1c2d3e4f5061728394a5b6c7d8e9f';
    const base = fakeGit({ counts: { [`${LIVE}..${SHA}`]: 6 }, state: { [MAIN_WT]: { dirty: [], ahead: 0, behind: 1 } } });
    let origin = SHA;
    let head = SHA;
    const git = (cwd, args) => {
      if (args[0] === 'rev-parse') return args.at(-1) === 'HEAD' ? head : origin;
      if (args[0] === 'merge') { base.calls.push({ cwd, args, lease: readLease(PATH) }); head = origin; return ''; }
      return base(cwd, args);
    };
    const clock = fakeClock({
      onSleep: (slept) => {
        if (slept === 2) {
          origin = LANDED;
          releaseLease({ repoPath: PATH, holder: { name: 'runner', kind: 'work-area' } });
        }
      },
    });
    const { out, stdout, stderr } = io();
    const seen = [];
    const code = await run([], {
      ...deps({ git, ...clock, spawnDeploy: async (options) => { seen.push({ ...options, lease: readLease(PATH) }); return { code: 0 }; } }),
      stdout,
      stderr,
    });
    assert.equal(code, 0);
    assert.equal(clock.slept(), 2, 'two polls, on merge\'s cadence');
    assert.match(out.stderr, /is held by runner for “merge round for memoro #812” — waiting for the window/u);
    assert.match(out.stderr, /waited 30s — the window is ours/u);
    const ff = base.calls.find((call) => call.args[0] === 'merge');
    assert.equal(ff.lease.errand, `deploy ${SHA}`, 'the fast-forward runs under the deploy\'s own lease');
    assert.equal(seen[0].sha, LANDED);
    assert.equal(seen[0].lease.held, false);
    const row = lastAttempt({ MC_WORK_ROOT: work });
    assert.equal(row.sha, LANDED, 'the row names the sha main stood on when the deploy got its turn');
    assert.equal(row.outcome, 'deployed');
  });

  it('refuses a second deploy while one is running, with its sha and start time from deploys.tsv', async () => {
    const env = { MC_WORK_ROOT: work };
    recordStart({ sha: LIVE, holder: 'martin@laptop', started: '2026-10-07T19:14:22.167Z', pid: 4242 }, env);
    const { out, stdout, stderr } = io();
    let ran = 0;
    let asked = 0;
    const code = await run([], {
      ...deps({
        alive: (pid) => pid === 4242,
        ask: () => { asked += 1; return 'y'; },
        spawnDeploy: async () => { ran += 1; return { code: 0 }; },
      }),
      stdout,
      stderr,
    });
    assert.equal(code, 1);
    assert.equal(ran, 0);
    assert.equal(asked, 0, 'nobody is asked a question that has no yes');
    assert.match(out.stderr, /a deploy of 9f8e7d6 has been running since 2026-10-07 19:14 \(martin@laptop, pid 4242\) — one deploy at a time; nothing was deployed/u);
    assert.equal(readLease(PATH).held, false, 'the lease was never taken');
    const [running, refused] = readDeploys(env);
    assert.equal(running.outcome, 'running', 'the running deploy\'s row is left alone');
    assert.equal(refused.outcome, 'refused');
    assert.match(refused.note, /a deploy of 9f8e7d6 is running — started 2026-10-07T19:14:22.167Z by martin@laptop/u);
  });

  it('a deploy that started while this one waited is refused under the lease', async () => {
    const env = { MC_WORK_ROOT: work };
    claimLease({ repoPath: PATH, errand: `deploy ${LIVE}`, holder: { name: 'other', kind: 'shell' } });
    const clock = fakeClock({
      onSleep: () => {
        recordStart({ sha: LIVE, holder: 'other', started: '2026-10-07T19:14:22.167Z', pid: 4242 }, env);
        releaseLease({ repoPath: PATH, holder: { name: 'other', kind: 'shell' } });
      },
    });
    const { out, stdout, stderr } = io();
    let ran = 0;
    const code = await run([], {
      ...deps({ alive: (pid) => pid === 4242, ...clock, spawnDeploy: async () => { ran += 1; return { code: 0 }; } }),
      stdout,
      stderr,
    });
    assert.equal(code, 1);
    assert.equal(ran, 0);
    assert.match(out.stderr, /a deploy of 9f8e7d6 has been running since 2026-10-07 19:14/u);
    assert.equal(readLease(PATH).held, false, 'its own lease is given back');
  });

  it('a running row whose process is gone is closed as failed, not a deploy in progress', async () => {
    const env = { MC_WORK_ROOT: work };
    recordStart({ sha: LIVE, holder: 'martin@laptop', started: '2026-10-07T19:14:22.167Z', pid: 4242 }, env);
    const { stdout, stderr } = io();
    const code = await run([], { ...deps({ alive: () => false }), stdout, stderr });
    assert.equal(code, 0);
    const [old, now] = readDeploys(env);
    assert.equal(old.outcome, 'failed');
    assert.equal(now.outcome, 'deployed');
    assert.equal(now.pid, String(process.pid), 'the row carries the pid it runs in');
  });
});

describe('mc deploy — the record', () => {
  it('writes the row before the script starts, and completes it when it ends', async () => {
    const { out, stdout, stderr } = io();
    let midway = null;
    const script = fakeScript({ steps: FULL_RUN, build: '23533', commit: SHA });
    const code = await run([], {
      ...deps({
        holder: { name: 'martin@laptop', kind: 'shell' },
        spawnDeploy: async (options) => {
          // What a second terminal would see while the deploy is running.
          midway = lastAttempt({ MC_WORK_ROOT: work });
          return script(options);
        },
      }),
      stdout,
      stderr,
    });
    assert.equal(code, 0);

    assert.equal(midway.outcome, 'running');
    assert.equal(midway.sha, SHA);
    assert.equal(midway.holder, 'martin@laptop');
    assert.equal(midway.ended, '');

    const rows = readDeploys({ MC_WORK_ROOT: work });
    assert.equal(rows.length, 1, 'the same row, completed — not a second one');
    assert.equal(rows[0].started, midway.started);
    assert.equal(rows[0].outcome, 'deployed');
    assert.equal(rows[0].build, '23533');
    assert.equal(rows[0].live_commit, SHA);
    assert.equal(rows[0].live_build, '23533');
    assert.equal(rows[0].stopped_at, '');
    assert.equal(rows[0].note, '');
    assert.match(rows[0].ended, /^\d{4}-\d\d-\d\dT/u);
    assert.match(out.stdout, /deployed — build 23533 · 1a2b3c4 verified live/u);
  });

  it('a script that dies at wrangler deploy leaves a row that says where', async () => {
    const { out, stdout, stderr } = io();
    const code = await run([], {
      ...deps({
        spawnDeploy: fakeScript({
          steps: ['Deploy source preflight', 'Dependency preflight', 'wrangler deploy'],
          code: 1,
          failure: 'npx wrangler deploy exited 1',
        }),
      }),
      stdout,
      stderr,
    });
    assert.equal(code, 1);
    const row = lastAttempt({ MC_WORK_ROOT: work });
    assert.equal(row.outcome, 'failed');
    assert.equal(row.stopped_at, 'wrangler deploy');
    assert.equal(row.live_commit, '');
    assert.equal(row.build, '');
    assert.match(row.note, /exit 1 — npx wrangler deploy exited 1/u);
    assert.equal(lastDeploy({ MC_WORK_ROOT: work }), null, 'a failure is not what is live');
    assert.match(out.stderr, /exited 1 at wrangler deploy/u);
  });

  it('names what production runs when the script said, instead of "may be part-way"', async () => {
    const { out, stdout, stderr } = io();
    const code = await run([], {
      ...deps({
        spawnDeploy: fakeScript({
          steps: ['Deploy source preflight', 'wrangler deploy'],
          code: 1,
          failure: 'wrangler deploy failed after 3 attempts: DNS could not resolve api.cloudflare.com',
          production: 'unchanged — no new Worker version was uploaded',
          retries: 2,
        }),
      }),
      stdout,
      stderr,
    });
    assert.equal(code, 1);
    const row = lastAttempt({ MC_WORK_ROOT: work });
    assert.match(row.note, /DNS could not resolve api\.cloudflare\.com — production unchanged — no new Worker version was uploaded$/u);
    assert.match(out.stderr, /exited 1 at wrangler deploy — production unchanged — no new Worker version was uploaded/u);
    assert.doesNotMatch(out.stderr, /may be part-way/u);
  });

  it('records a green deploy that needed retries', async () => {
    const { out, stdout, stderr } = io();
    await run([], { ...deps({ spawnDeploy: fakeScript({ steps: FULL_RUN, retries: 1 }) }), stdout, stderr });
    const row = lastDeploy({ MC_WORK_ROOT: work });
    assert.equal(row.outcome, 'deployed');
    assert.equal(row.note, 'went through after 1 retry on network faults');
    assert.match(out.stdout, /verified live \(after 1 retry on network faults\)/u);
  });

  it('says so when a green deploy verified no live version', async () => {
    const { stdout, stderr } = io();
    await run([], { ...deps({ spawnDeploy: fakeScript({ steps: FULL_RUN, verify: false }) }), stdout, stderr });
    const row = lastDeploy({ MC_WORK_ROOT: work });
    assert.equal(row.outcome, 'deployed');
    assert.equal(row.build, '23533', 'the banner still says what shipped');
    assert.equal(row.live_commit, '', 'but nothing was verified against production');
    assert.match(row.note, /verified no live version/u);
  });

  it('a no at the question is a refused row, so the brief sees a deploy somebody meant', async () => {
    const { stdout, stderr } = io();
    await run([], { ...deps({ ask: () => 'n', holder: { name: 'martin', kind: 'shell' } }), stdout, stderr });
    const row = lastAttempt({ MC_WORK_ROOT: work });
    assert.equal(row.outcome, 'refused');
    assert.equal(row.sha, SHA);
    assert.equal(row.holder, 'martin');
    assert.match(row.note, /answered no/u);
    assert.equal(row.started, row.ended);
  });

  it('no terminal is a refused row too', async () => {
    const { stdout, stderr } = io();
    assert.equal(await run([], { ...deps({ interactive: () => false }), stdout, stderr }), 2);
    assert.match(lastAttempt({ MC_WORK_ROOT: work }).note, /no terminal/u);
  });

  it('a repository held past the wait is a refused row naming who holds it', async () => {
    claimLease({ repoPath: PATH, errand: 'gate round #591', holder: { name: 'runner', kind: 'work-area' } });
    const { stdout, stderr } = io();
    await run([], { ...deps(fakeClock()), stdout, stderr });
    const row = lastAttempt({ MC_WORK_ROOT: work });
    assert.equal(row.outcome, 'refused');
    assert.match(row.note, /held by runner — gate round #591/u);
  });

  it('--dry-run deploys nothing and records nothing', async () => {
    const { stdout, stderr } = io();
    await run(['--dry-run'], { ...deps(), stdout, stderr });
    assert.deepEqual(readDeploys({ MC_WORK_ROOT: work }), []);
  });

  it('the row it wrote is what the next reading calls live', async () => {
    const { stdout, stderr } = io();
    await run([], { ...deps({ spawnDeploy: fakeScript({ steps: FULL_RUN, build: '900' }) }), stdout, stderr });

    // No `lastDeploy` in deps this time: the verb's own default is the reader
    // in deploys.js, and it is reading the file the deploy above wrote.
    const second = deps({ git: fakeGit({ counts: { [`${SHA}..${SHA}`]: 0 } }) });
    delete second.lastDeploy;
    const { out, stdout: out2, stderr: err2 } = io();
    await run(['--dry-run'], { ...second, stdout: out2, stderr: err2 });
    assert.match(out.stdout, /live now 1a2b3c4 \(build 900\) — deploys\.tsv/u);
    assert.match(out.stdout, /nothing new would ship/u);
  });
});

describe('the spawn itself', () => {
  // The one place a real `npm run deploy` is started, against a package.json
  // that only prints. Everything the row keeps comes through this pipe, and a
  // tee that captured without echoing would leave the person watching a blank
  // terminal for twenty minutes — which no faked spawn could ever show.
  it('echoes the script to the terminal and captures it at the same time', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'mc-deploy-spawn-'));
    const line = '\\n\\u001b[36m▸ wrangler deploy\\u001b[0m\\n';
    writeFileSync(join(dir, 'package.json'), JSON.stringify({
      name: 'not-really-memoro',
      private: true,
      scripts: { deploy: `node -e "process.stdout.write('${line}'); process.exit(3)"` },
    }));
    let captured = '';
    const { out, stdout, stderr } = io();
    const result = await spawnDeployDefault({
      cwd: dir, env: process.env, onOutput: (chunk) => { captured += chunk; }, stdout, stderr,
    });
    assert.equal(result.code, 3);
    assert.match(captured, /▸ wrangler deploy/u);
    assert.match(out.stdout, /▸ wrangler deploy/u);
    assert.equal(readScriptOutput(captured).stopped_at, 'wrangler deploy');
  });
});

describe('what the script said', () => {
  it('reads the step it stopped at and the version it verified, through the colours', () => {
    const said = readScriptOutput([
      stepLine('wrangler deploy'),
      stepLine('Verify live version'),
      `${DIM}  Live /api/version verified: build 23533 · ${SHA}${RESET}\n`,
      `\n${GREEN}${BOLD}✓ Deploy complete${RESET} ${DIM}build 23533 · ${SHA}${RESET}\n`,
    ].join(''));
    assert.equal(said.stopped_at, 'Verify live version');
    assert.equal(said.live_commit, SHA);
    assert.equal(said.live_build, '23533');
    assert.equal(said.build, '23533');
    assert.equal(said.verified, true);
  });

  it('keeps the failure message under ✗ Deploy failed', () => {
    const said = readScriptOutput(`${stepLine('Dependency preflight')}\n${RED}✗ Deploy failed${RESET}\n${DIM}npm run deps:ensure exited 1${RESET}\n`);
    assert.equal(said.stopped_at, 'Dependency preflight');
    assert.equal(said.failure, 'npm run deps:ensure exited 1');
    assert.equal(said.verified, false);
  });

  it('reads what production runs from the failure summary, not from a retry on the way', () => {
    const said = readScriptOutput([
      stepLine('wrangler deploy'),
      `${YELLOW}  ↻ wrangler deploy --containers-rollout=none failed after 0s: DNS could not resolve api.cloudflare.com.${RESET}\n`,
      `${DIM}    Production meanwhile: unchanged — no new Worker version was uploaded.${RESET}\n`,
      `\n${RED}${BOLD}✗ Deploy failed${RESET}\n`,
      `${DIM}wrangler deploy --containers-rollout=none failed after 3 attempts: DNS could not resolve api.cloudflare.com${RESET}\n\n`,
      `  ${BOLD}Failed at  ${RESET}wrangler deploy (attempt 3 of 3)\n`,
      `  ${BOLD}Cause      ${RESET}DNS could not resolve api.cloudflare.com — a network fault, not the build; a rerun usually goes through\n`,
      `  ${BOLD}Production ${RESET}unchanged — no new Worker version was uploaded\n`,
    ].join(''));
    assert.equal(said.stopped_at, 'wrangler deploy');
    assert.equal(said.failure, 'wrangler deploy --containers-rollout=none failed after 3 attempts: DNS could not resolve api.cloudflare.com');
    assert.equal(said.production, 'unchanged — no new Worker version was uploaded');
    assert.match(said.cause, /^DNS could not resolve api\.cloudflare\.com — a network fault/u);
    assert.equal(said.retries, 1);
  });

  it('counts the retries of a deploy that went through, and takes no production from them', () => {
    const said = readScriptOutput([
      stepLine('wrangler deploy'),
      `${YELLOW}  ↻ wrangler deploy failed after 0s: a request to Cloudflare failed (fetch failed).${RESET}\n`,
      `${DIM}    Production meanwhile: unchanged — no new Worker version was uploaded.${RESET}\n`,
      `\n${GREEN}${BOLD}✓ Deploy complete${RESET} ${DIM}build 23533 · ${SHA}${RESET}\n`,
    ].join(''));
    assert.equal(said.retries, 1);
    assert.equal(said.production, '');
    assert.equal(said.build, '23533');
  });

  it('is empty cells and not a crash when the script says none of it', () => {
    assert.deepEqual(readScriptOutput('some other tool wrote this\n'), {
      stopped_at: '', build: '', live_commit: '', live_build: '', verified: false, failure: '',
      production: '', cause: '', retries: 0,
    });
    assert.equal(readScriptOutput('').stopped_at, '');
    assert.equal(readScriptOutput(null).build, '');
  });
});

describe('a deploy that was stopped', () => {
  // A real repository: what counts as a stamp is read from git's own diff,
  // and a stub could only agree with the regex it was written against.
  function stampedRepo() {
    const dir = mkdtempSync(join(tmpdir(), 'mc-deploy-stamps-'));
    const g = (...args) => execFileSync('git', ['-C', dir, ...args], { encoding: 'utf8' });
    g('init', '-q');
    mkdirSync(join(dir, 'public'));
    mkdirSync(join(dir, 'src'));
    writeFileSync(join(dir, 'public/sw.js'), "// shell cache\nconst CACHE_VERSION = 'dev-brand';\nconst SHELL = 1;\n");
    writeFileSync(join(dir, 'src/version.js'), '/**\n * stubs\n */\nexport const VERSION = "1.0.0";\nexport const COMMIT = "dev";\nexport const BUILD_NUMBER = 0;\n');
    g('add', '.');
    g('-c', 'user.name=t', '-c', 'user.email=t@t', 'commit', '-qm', 'base');
    writeFileSync(join(dir, 'public/sw.js'), "// shell cache\nconst CACHE_VERSION = 'v957cebb3d0b7';\nconst SHELL = 1;\n");
    writeFileSync(join(dir, 'src/version.js'), [
      '// Auto-generated by scripts/inject-version.mjs at deploy time. Do not edit.',
      'export const VERSION = "1.0.0";',
      'export const COMMIT = "957cebb";',
      'export const COMMIT_FULL = "957cebb3d0b7b294abfe5bb38bcb100eafa99b01";',
      'export const BUILD_TIME = "2026-10-05T20:05:01.000Z";',
      'export const BUILD_NUMBER = 24804;',
      '',
    ].join('\n'));
    return dir;
  }

  it('tells a deploy\'s leftover stamps from somebody\'s work', () => {
    const dir = stampedRepo();
    const state = worktreeState({ worktree: dir });
    assert.equal(state.dirty.length, 2);
    assert.equal(leftoverStamps({ worktree: dir, dirty: state.dirty }), true);

    writeFileSync(join(dir, 'public/sw.js'), "// shell cache\nconst CACHE_VERSION = 'v957cebb3d0b7';\nconst SHELL = 2;\n");
    assert.equal(leftoverStamps({ worktree: dir, dirty: worktreeState({ worktree: dir }).dirty }), false, 'an edit beside the stamp is work');
  });

  it('a stamp file beside any other change is not leftovers', () => {
    const dir = stampedRepo();
    writeFileSync(join(dir, 'notes.txt'), 'mine\n');
    assert.equal(leftoverStamps({ worktree: dir, dirty: worktreeState({ worktree: dir }).dirty }), false);
  });

  it('a row left running is closed when the next deploy takes the lease', async () => {
    const env = { MC_WORK_ROOT: work };
    recordStart({ sha: LIVE, holder: 'martin@laptop', started: '2026-10-05T20:04:38.428Z' }, env);
    const { out, stdout, stderr } = io();
    await run([], { ...deps({ spawnDeploy: fakeScript({ steps: FULL_RUN }) }), stdout, stderr });

    const [old, now] = readDeploys(env);
    assert.equal(old.outcome, 'failed');
    assert.equal(old.ended, '', 'when it stopped is not known');
    assert.match(old.note, /never came back — its process was gone when the next deploy began/u);
    assert.equal(now.outcome, 'deployed');
    assert.match(out.stdout, /the deploy of 9f8e7d6 started 2026-10-05 20:04 never came back/u);
  });

  it('says the deploy was stopped, and what production runs', async () => {
    const { out, stdout, stderr } = io();
    const script = fakeScript({
      steps: ['Deploy source preflight', 'wrangler deploy'],
      code: 130,
      failure: 'Deploy interrupted by SIGINT',
      production: 'unchanged — no new Worker version was uploaded',
    });
    const code = await run([], {
      ...deps({ spawnDeploy: async (options) => ({ ...(await script(options)), interrupted: 'SIGINT' }) }),
      stdout,
      stderr,
    });
    assert.equal(code, 130);
    assert.match(out.stderr, /the deploy was stopped by SIGINT at wrangler deploy — production unchanged/u);
    const row = lastAttempt({ MC_WORK_ROOT: work });
    assert.equal(row.outcome, 'failed');
    assert.match(row.note, /interrupted by SIGINT — production unchanged/u);
  });

  it('mc outlives ^C: it passes it on and waits for the script to finish', async () => {
    // A script that does what deploy.mjs does on a signal: say so, then exit
    // 130. Were mc to die with the signal, nothing would read that summary.
    const dir = mkdtempSync(join(tmpdir(), 'mc-deploy-signal-'));
    writeFileSync(join(dir, 'script.js'), [
      "process.on('SIGTERM', () => { console.log('✗ Deploy failed'); console.log('Production unchanged'); process.exit(130); });",
      "console.log('ready'); setInterval(() => {}, 1000);",
    ].join('\n'));
    writeFileSync(join(dir, 'package.json'), JSON.stringify({
      name: 'not-really-memoro', private: true, scripts: { deploy: 'node script.js' },
    }));
    const signals = new EventEmitter();
    let captured = '';
    const { out, stdout, stderr } = io();
    const result = await spawnDeployDefault({
      cwd: dir,
      env: process.env,
      signals,
      stdout,
      stderr,
      onOutput: (chunk) => {
        captured += chunk;
        if (/ready/u.test(chunk)) signals.emit('SIGINT', 'SIGINT');
      },
    });
    assert.equal(result.interrupted, 'SIGINT');
    assert.equal(result.code, 130);
    assert.equal(readScriptOutput(captured).production, 'unchanged');
    assert.match(out.stderr, /mc: SIGINT — stopping the deploy; waiting for it/u);
    assert.equal(signals.listenerCount('SIGINT'), 0, 'the handlers go with the spawn');
  });
});
