/**
 * Vault → PreToolUse hook (§12e).
 *
 * Phase 3 of the vault. Once the lifecycle materialises tokens at known
 * paths (phase 2), we need to STOP the LLM from reading those paths via
 * Read or Bash tool calls. This module installs a per-session bash hook
 * inside the worktree's `.claude/` directory and wires a PreToolUse
 * entry into the worktree's `.claude/settings.json`.
 *
 * Boundaries:
 *   - Project-scoped only. We NEVER touch `~/.claude/settings.json` or
 *     `~/.claude/hooks/` (the user-global surface). All paths under the
 *     worktree itself.
 *   - Surgical install / uninstall. Other PreToolUse entries (memoro's
 *     `block-prod-wrangler.sh`, etc.) stay untouched. We tag our own
 *     entry with `_mc_vault_managed: true` so the uninstaller can find
 *     and remove only its own row.
 *   - Idempotent. Re-install when already installed = no-op. Re-
 *     uninstall = no-op. Tests cover both.
 *   - Fail-open on broken state. If the worktree path is missing, if
 *     the manifest is unreadable, if settings.json is malformed JSON —
 *     the hook installer logs nothing on stdout/stderr (callers
 *     soft-degrade) and returns ok:false with a reason. The hook
 *     script itself defaults to ALLOW when its manifest is missing or
 *     malformed (a broken state file must not brick the user's
 *     session).
 *
 * No-leak invariant: the hook script's denial message refers to
 * "a managed vault path" generically. It NEVER echoes the matched
 * path bytes, so even debug logs of the hook output don't disclose
 * which file was queried.
 */

import { existsSync } from 'node:fs';
import {
  mkdir, writeFile, readFile, chmod, unlink,
} from 'node:fs/promises';
import { join, dirname } from 'node:path';

const MANAGED_FLAG = '_mc_vault_managed';

/**
 * Per-worktree settings path. `<worktree>/.claude/settings.json`.
 */
export function settingsPathFor(worktreePath) {
  return join(worktreePath, '.claude', 'settings.json');
}

/**
 * Per-worktree hook script path. The session id is baked into the
 * filename so multiple sessions sharing one worktree (unlikely but
 * possible during testing) don't trample each other's scripts.
 */
export function hookScriptPathFor(worktreePath, sessionId) {
  return join(worktreePath, '.claude', 'hooks', `mc-vault-block-${sessionId}.sh`);
}

/**
 * Render the per-session hook script. The manifest path + denial
 * message are baked in at render time so the script has zero env-var
 * dependencies at runtime (faster + more predictable).
 *
 * The bash script protocol matches `~/.claude/hooks/block-secret-reads.sh`:
 *   - read stdin JSON
 *   - extract tool_input.file_path + tool_input.command (treat the
 *     concatenation as the haystack)
 *   - for each materialised path, see if the haystack contains it
 *   - on match: emit the deny JSON envelope and exit 0
 *   - on no match (or any internal error): exit 0 silently (allow)
 */
export function renderHookScript({ manifestPath, sessionId }) {
  if (!manifestPath || typeof manifestPath !== 'string') {
    throw new Error('renderHookScript: manifestPath required');
  }
  if (!sessionId || typeof sessionId !== 'string') {
    throw new Error('renderHookScript: sessionId required');
  }
  // We deliberately quote the manifest path with single quotes so any
  // characters in MC_HOME stay literal. Session id is constrained by
  // the NAME_RE regex in `mc new`, so its safety follows from there.
  return `#!/usr/bin/env bash
# PreToolUse hook installed by memoro-cli for session: ${sessionId}
# Generated by src/mc/vault/hook.js — do not edit by hand.
#
# Blocks Read / Bash tool calls that target paths materialised into
# this worktree by \`mc vault\` (phase 2). Fail-open on broken state:
# missing or malformed manifest = silent allow, so a stale hook never
# bricks the user's session.

set -u

MANIFEST='${manifestPath}'

# Drain stdin (Claude Code provides a small JSON envelope).
input="$(cat)"

# Fail-open if the manifest is missing or unreadable.
if [ ! -f "$MANIFEST" ]; then
  exit 0
fi

# Extract paths. We pipe the manifest through jq once (fast).
paths="$(jq -r '.materialised[]?.location.path // empty' "$MANIFEST" 2>/dev/null)" || exit 0
if [ -z "$paths" ]; then
  exit 0
fi

# Extract target string: file_path + command, joined with a space.
target="$(printf '%s' "$input" | jq -r '[.tool_input.command // "", .tool_input.file_path // ""] | join(" ")' 2>/dev/null)" || exit 0
if [ -z "$target" ]; then
  exit 0
fi

# Plain substring match. Each path is on its own line; loop until we
# either match or exhaust the list. We do NOT echo the path on match —
# the denial message is generic to preserve the no-leak invariant.
while IFS= read -r p; do
  [ -z "$p" ] && continue
  case "$target" in
    *"$p"*)
      cat <<'JSON'
{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": "Blocked by memoro-cli vault hook: target matches a managed vault path materialised for this session. The cleartext token must not be read by the LLM. If you genuinely need this value, ask the user."
  }
}
JSON
      exit 0
      ;;
  esac
done <<< "$paths"

exit 0
`;
}

/**
 * The PreToolUse-entry shape we inject. One entry per matcher (Read,
 * Bash). The `_mc_vault_managed: true` flag is how the uninstaller
 * recognises its own rows without false-matching the user's other
 * project hooks.
 *
 * Claude Code ignores unknown top-level keys on entry objects, so the
 * flag is safe to embed inline. (Confirmed by inspecting memoro's
 * own .claude/settings.json shape — entries use only `matcher` +
 * `hooks` and Claude Code reads them fine even when extra metadata
 * sits alongside.)
 */
function buildEntries(scriptPath) {
  const command = scriptPath;
  return [
    {
      [MANAGED_FLAG]: true,
      matcher: 'Bash',
      hooks: [{ type: 'command', command }],
    },
    {
      [MANAGED_FLAG]: true,
      matcher: 'Read',
      hooks: [{ type: 'command', command }],
    },
  ];
}

/**
 * Read settings.json from disk; return { settings, existed, malformed }.
 * Soft-degrade — a malformed file becomes `malformed: true` so callers
 * can decide whether to abort or overwrite.
 */
async function loadSettings(path, { readFile: rf = readFile } = {}) {
  if (!existsSync(path)) {
    return { settings: {}, existed: false, malformed: false };
  }
  try {
    const raw = await rf(path, 'utf8');
    if (!raw.trim()) {
      return { settings: {}, existed: true, malformed: false, empty: true };
    }
    const parsed = JSON.parse(raw);
    if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
      return { settings: {}, existed: true, malformed: true };
    }
    return { settings: parsed, existed: true, malformed: false };
  } catch {
    return { settings: {}, existed: true, malformed: true };
  }
}

/**
 * Insert the managed entries into settings.PreToolUse. Pure function —
 * the input is treated as immutable (deep-cloned at the top level only
 * for the keys we touch).
 *
 * Returns a new settings object with the entries appended (idempotent:
 * if a managed entry with the same matcher already exists, replace it
 * in place so re-install doesn't grow the array).
 */
export function withMcEntriesInserted(settings, scriptPath) {
  const next = { ...settings };
  const hooks = { ...(next.hooks || {}) };
  const preToolUse = Array.isArray(hooks.PreToolUse) ? [...hooks.PreToolUse] : [];

  const mcEntries = buildEntries(scriptPath);
  for (const newEntry of mcEntries) {
    const existingIdx = preToolUse.findIndex((e) =>
      e && typeof e === 'object' && e[MANAGED_FLAG] === true && e.matcher === newEntry.matcher,
    );
    if (existingIdx >= 0) {
      preToolUse[existingIdx] = newEntry;
    } else {
      preToolUse.push(newEntry);
    }
  }

  hooks.PreToolUse = preToolUse;
  next.hooks = hooks;
  return next;
}

/**
 * Remove ALL mc-managed PreToolUse entries from settings.PreToolUse.
 * Pure function — returns a new settings object.
 *
 * Also collapses empty containers: if PreToolUse becomes [], drop the
 * key; if hooks ends up empty, drop it. This is what makes the
 * "byte-identical pre/post" invariant hold for the no-existing-hooks
 * case.
 */
export function withMcEntriesRemoved(settings) {
  if (!settings || typeof settings !== 'object') return settings;
  const hooks = settings.hooks;
  if (!hooks || typeof hooks !== 'object') return settings;
  const preToolUse = hooks.PreToolUse;
  if (!Array.isArray(preToolUse)) return settings;

  const kept = preToolUse.filter((e) =>
    !(e && typeof e === 'object' && e[MANAGED_FLAG] === true),
  );

  if (kept.length === preToolUse.length) return settings; // nothing to do

  const nextHooks = { ...hooks };
  if (kept.length === 0) {
    delete nextHooks.PreToolUse;
  } else {
    nextHooks.PreToolUse = kept;
  }

  const next = { ...settings };
  if (Object.keys(nextHooks).length === 0) {
    delete next.hooks;
  } else {
    next.hooks = nextHooks;
  }
  return next;
}

/**
 * Install the per-session hook:
 *   1. Write the script to <worktree>/.claude/hooks/mc-vault-block-<sid>.sh
 *      (mode 0700; idempotent overwrite).
 *   2. Read <worktree>/.claude/settings.json (or treat as empty if absent).
 *   3. Insert two mc-managed PreToolUse entries (Bash + Read).
 *   4. Write settings.json back (pretty-printed with 2-space indent for
 *      readable diffs).
 *
 * Returns { ok, installedSettingsPath, hookScriptPath, settingsCreated,
 *           reason?, hint? }.
 *
 * The caller (lifecycle.materialiseForSession) records
 * { installedSettingsPath, hookScriptPath } into the session manifest so
 * uninstall is unambiguous. If settings.json existed before install,
 * `settingsCreated: false` so uninstall knows to preserve the file
 * (vs delete it outright when mc created it).
 */
export async function installHook({
  worktreePath,
  sessionId,
  manifestPath,
  deps = {},
} = {}) {
  if (!worktreePath || typeof worktreePath !== 'string') {
    return { ok: false, reason: 'worktreePath-required' };
  }
  if (!sessionId || typeof sessionId !== 'string') {
    return { ok: false, reason: 'sessionId-required' };
  }
  if (!manifestPath || typeof manifestPath !== 'string') {
    return { ok: false, reason: 'manifestPath-required' };
  }
  if (!existsSync(worktreePath)) {
    return { ok: false, reason: 'worktree-missing' };
  }

  const writeFn = deps.writeFile || writeFile;
  const mkdirFn = deps.mkdir || mkdir;
  const chmodFn = deps.chmod || chmod;

  const scriptPath = hookScriptPathFor(worktreePath, sessionId);
  const settingsPath = settingsPathFor(worktreePath);

  try {
    await mkdirFn(dirname(scriptPath), { recursive: true, mode: 0o700 });
    await mkdirFn(dirname(settingsPath), { recursive: true });
  } catch (err) {
    return { ok: false, reason: `mkdir-failed: ${err.message}` };
  }

  // Render + write the hook script.
  const script = renderHookScript({ manifestPath, sessionId });
  try {
    await writeFn(scriptPath, script, { mode: 0o700 });
    // Belt-and-braces: explicit chmod in case writeFile's mode was
    // honoured under umask.
    await chmodFn(scriptPath, 0o700).catch(() => {});
  } catch (err) {
    return { ok: false, reason: `script-write-failed: ${err.message}` };
  }

  // Load + patch settings.
  const loaded = await loadSettings(settingsPath, { readFile: deps.readFile });
  if (loaded.malformed) {
    return {
      ok: false,
      reason: 'settings-malformed',
      hint: `existing ${settingsPath} is not valid JSON; refusing to overwrite`,
    };
  }
  const next = withMcEntriesInserted(loaded.settings, scriptPath);
  try {
    await writeFn(settingsPath, JSON.stringify(next, null, 2) + '\n', { mode: 0o600 });
  } catch (err) {
    return { ok: false, reason: `settings-write-failed: ${err.message}` };
  }

  return {
    ok: true,
    installedSettingsPath: settingsPath,
    hookScriptPath: scriptPath,
    settingsCreated: !loaded.existed,
  };
}

/**
 * Uninstall the per-session hook. Surgical:
 *   1. Read settings.json.
 *   2. Strip mc-managed PreToolUse entries.
 *   3. If `settingsCreatedByMc` AND post-strip settings is byte-equal to
 *      `{}` → delete the file outright.
 *   4. Otherwise write back the stripped settings.
 *   5. Delete the hook script.
 *
 * Idempotent: a second call is a no-op (no managed entries to find,
 * script already gone).
 */
export async function uninstallHook({
  worktreePath,
  sessionId,
  settingsCreatedByMc = false,
  deps = {},
} = {}) {
  if (!worktreePath || typeof worktreePath !== 'string') {
    return { ok: false, reason: 'worktreePath-required' };
  }
  if (!sessionId || typeof sessionId !== 'string') {
    return { ok: false, reason: 'sessionId-required' };
  }

  const writeFn = deps.writeFile || writeFile;
  const unlinkFn = deps.unlink || unlink;
  const exists = deps.existsSync || existsSync;

  const scriptPath = hookScriptPathFor(worktreePath, sessionId);
  const settingsPath = settingsPathFor(worktreePath);

  let settingsRemoved = false;
  let entriesRemoved = false;

  if (exists(settingsPath)) {
    const loaded = await loadSettings(settingsPath, { readFile: deps.readFile });
    if (!loaded.malformed) {
      const stripped = withMcEntriesRemoved(loaded.settings);
      const changed = stripped !== loaded.settings;
      entriesRemoved = changed;
      const isEmpty = Object.keys(stripped || {}).length === 0;
      if (settingsCreatedByMc && isEmpty) {
        try {
          await unlinkFn(settingsPath);
          settingsRemoved = true;
        } catch { /* best effort */ }
      } else if (changed) {
        try {
          await writeFn(settingsPath, JSON.stringify(stripped, null, 2) + '\n', { mode: 0o600 });
        } catch { /* best effort */ }
      }
    }
    // Malformed settings → leave the file alone. We can't safely strip
    // entries we can't parse, and we don't want to nuke the user's
    // file.
  }

  if (exists(scriptPath)) {
    try { await unlinkFn(scriptPath); } catch { /* best effort */ }
  }

  return { ok: true, settingsRemoved, entriesRemoved };
}
