export const RUNTIME_SECRET_ENV_NAMES = Object.freeze([
  'MEMORO_TOKEN',
  'MEMORO_BROKER_TOKEN',
  'MC_VAULT_PASSPHRASE',
  'MC_CLOUD_GIT_TOKEN',
  'MC_CLOUD_GIT_SECRET_CAPABILITY',
  'MC_GIT_CLONE_TOKEN',
  'GH_TOKEN',
  'GITHUB_TOKEN',
  'GH_ENTERPRISE_TOKEN',
  'GITHUB_ENTERPRISE_TOKEN',
  'GH_CONFIG_DIR',
  'MC_CODEX_API_KEY',
  'OPENAI_API_KEY',
  'ANTHROPIC_API_KEY',
  'ANTHROPIC_AUTH_TOKEN',
  'CLAUDE_API_KEY',
  'CLAUDE_CODE_OAUTH_TOKEN',
  'GEMINI_API_KEY',
  'GOOGLE_API_KEY',
  'GOOGLE_APPLICATION_CREDENTIALS',
  'GOOGLE_OAUTH_ACCESS_TOKEN',
  'CLOUDSDK_AUTH_ACCESS_TOKEN',
  'AWS_ACCESS_KEY_ID',
  'AWS_SECRET_ACCESS_KEY',
  'AWS_SESSION_TOKEN',
  'AWS_SECURITY_TOKEN',
  'AWS_SHARED_CREDENTIALS_FILE',
  'AWS_CONFIG_FILE',
  'AWS_WEB_IDENTITY_TOKEN_FILE',
  'AWS_PROFILE',
  'CLOUDFLARE_API_TOKEN',
  'CLOUDFLARE_API_KEY',
  'CF_API_TOKEN',
  'CF_API_KEY',
  'WRANGLER_API_TOKEN',
  'SSH_AUTH_SOCK',
  'SSH_AGENT_PID',
  'SSH_ASKPASS',
  'SSH_ASKPASS_REQUIRE',
  'GIT_ASKPASS',
  'GIT_SSH',
  'GIT_SSH_COMMAND',
  'GIT_CONFIG_GLOBAL',
  'GIT_CONFIG_SYSTEM',
  'NETRC',
]);

export function scrubRuntimeSecretsFromEnv(env = process.env) {
  const next = { ...(env || {}) };
  for (const name of RUNTIME_SECRET_ENV_NAMES) {
    delete next[name];
  }
  return next;
}

export function scrubRuntimeSecretsInPlace(env) {
  if (!env || typeof env !== 'object') return env;
  for (const name of RUNTIME_SECRET_ENV_NAMES) {
    delete env[name];
  }
  return env;
}
